ifeq ($(findstring 86, $(ProgramFiles)), )
	PROGFILES := C:/Program Files
else
	PROGFILES := C:/Program Files (x86)
endif

GNU_INSTALL_ROOT := /home/Anthony/Project_Shiba/firmware/sdk/toolchain
GNU_VERSION := 4.9.3
GNU_PREFIX := arm-none-eabi

